hamburger menu created inapp.components.html, menu added to home.page…
cimem-hu/sk0 pull request #46
Opened 2024-02-15 20:42 UTC by Jankita58

…, it shows username

2024-02-15 21:01 UTC, rolcho requested changes
Looking good, the missing part is to merge origin/dev into your branch

2024-02-15 21:01 UTC, rolcho commented on sk0-front/src/app/app.component.ts
> +  }
I think it is different in the dev bev branch. There should be a BehavorSubject in the dev branch.

```suggestion
  userName$ = this.authService.userName
  
  constructor(private authService: AuthService) {}
```

2024-02-15 21:01 UTC, rolcho commented on sk0-front/src/app/app.component.html
> +          {{ userName }}
```suggestion
          {{ userName$ | async }}
```

2024-02-16 06:51 UTC, rolcho approved these changes
Looking good for me

2024-02-16 17:34 UTC, markkovari approved these changes

2024-02-19 10:32 UTC, bendesbeus approved these changes

2024-02-19 12:39 UTC, merged