SK0 37
cimem-hu/sk0 pull request #57
Opened 2024-02-22 14:34 UTC by rolcho

- profile page created
- fix(be): UsersService test
- updated test
- fix(fe): profile page
- fix(be) UsersService and test

2024-02-22 16:14 UTC, markkovari requested changes
Good job. We should not really have bigger PRs. This is a good context boundary.

2024-02-22 16:14 UTC, markkovari commented on sk0-back/src/users/controllers/users.controller.ts
> +      console.log("hello");
Should be removed.

2024-02-22 16:14 UTC, markkovari commented on sk0-front/jest.config.js
> +  ],
🙏

2024-02-22 16:14 UTC, markkovari commented on sk0-front/src/app/profile/profile.page.ts
> +    /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{6,}$/;
Later we might want to move the reused part into a common service or util. But looks good for now.

2024-02-22 16:14 UTC, markkovari commented on sk0-front/src/app/profile/profile.page.ts
> +        }
```suggestion
          this.profileForm.get("name")?.setValue(response.name);
          this.profileForm.get("email")?.setValue(response.email);
        }
```

2024-02-22 16:14 UTC, markkovari commented on sk0-front/src/app/profile/profile.page.html
> +
```suggestion
```

2024-02-22 16:45 UTC, rolcho commented on sk0-front/src/app/profile/profile.page.ts
> +    /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{6,}$/;
@markkovari Yes we should talk about how and where to store

2024-02-22 16:47 UTC, markkovari commented on sk0-front/src/app/profile/profile.page.ts
> +    /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{6,}$/;
Yesyes, closing this convo. :pray:

2024-02-22 16:50 UTC, rolcho commented on sk0-back/src/users/controllers/users.controller.ts
> +      console.log("hello");
sure

2024-02-22 17:03 UTC, markkovari approved these changes

2024-02-22 18:45 UTC, bendesbeus approved these changes

2024-02-22 19:36 UTC, Jankita58 approved these changes

2024-02-23 09:31 UTC, markkovari approved these changes

2024-02-23 12:37 UTC, merged