refactor(fe): ngrx add to app, auth state create
cimem-hu/sk0 pull request #70
Opened 2024-03-16 15:03 UTC by rolcho

2024-03-17 21:38 UTC, markkovari approved these changes

2024-03-18 05:38 UTC, markkovari requested changes

2024-03-18 05:38 UTC, markkovari commented on sk0-front/src/app/profile/profile.page.html
> +                  value="{{email$| async}}"
```suggestion
                  value="{{email$ | async}}"
```

2024-03-18 05:38 UTC, markkovari approved these changes

2024-03-18 07:52 UTC, markkovari requested changes

2024-03-18 07:52 UTC, markkovari commented on sk0-front/src/app/auth/store/auth.reducer.spec.ts
> +  const mockInitialAuthState: AuthState = {
Why is that a 'mock' value? I think this is the actual value and not a mock of it. If you are testing the reducer functions it should not be mocked.

2024-03-18 08:12 UTC, markkovari approved these changes

2024-03-18 13:07 UTC, bendesbeus approved these changes

2024-03-19 13:08 UTC, markkovari approved these changes

2024-03-22 15:25 UTC, merged