style(e2e): button selector
cimem-hu/sk0 pull request #93
Opened 2024-04-20 07:47 UTC by rolcho

2024-04-20 09:07 UTC, markkovari approved these changes

2024-04-20 15:42 UTC, markkovari requested changes

2024-04-20 15:42 UTC, markkovari commented on sk0-back/src/main.ts
> +  console.log({ origin });
```suggestion
```

2024-04-20 15:57 UTC, rolcho commented on sk0-back/src/main.ts
> +  console.log({ origin });
:open_mouth: Sorry

2024-04-20 16:35 UTC, markkovari approved these changes

2024-04-25 14:44 UTC, Thomas851204 approved these changes
Didnt find the button selector at first, had to dig through the commits :D
Also thanks for the docker+cors cleanup.
Good to go.

2024-04-25 14:44 UTC, merged